
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Shared/Footer";
import Navbar from "@/components/Shared/Navbar";
import AuthProvider from "@/Services/AuthProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: {
    default: "Car Doctor Pro",
    template: "%s | Car Doctor Pro"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const pathName=usePathname()
  // const hideNavFooter= pathName==='dashboard' || pathName==='login' ||pathName==='signup';
  return (
    <html lang="en" data-theme='carDoctorTheme'>
      <head>
        <link rel="shortcut icon" href="/assets/logo.svg" type="image/x-icon" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <Navbar />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
